name: Sync with Main Repo

on:
  push:
    branches:
      - main

jobs:
  fetch-webhooks-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get All Webhook URL
        id: get_webhooks
        run: |
          URLS=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://api.github.com/repos/DaizeDong/BasicUtils/hooks \
                 | jq -r '.[] | select(.active == true) | .config.url')
          echo "WEBHOOK_URLS=${URLS}" >> $GITHUB_ENV

      - name: Send Sync Signal to Main Repos
        run: |
          for url in $WEBHOOK_URLS; do
            echo "Triggering: $url"
            curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
                 -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
                 "$url" \
                 -d '{"event_type": "update_submodule"}'
          done
